import { createOxfmtConfig } from '@myfunnow/web-core-config-format'

export default createOxfmtConfig({
  // Generated by funnow-group-figma token-transformer and synced by CI
  ignorePatterns: ['src/tokens/**'],
})
