import { createOxfmtConfig } from '@myfunnow/web-core-config-format'

export default createOxfmtConfig({
  ignorePatterns: [
    // Generated by funnow-group-figma token-transformer and synced by CI
    'src/tokens/**',
    // Blueprint templates contain {{ }} placeholders that are not valid code
    'blueprint-templates/**',
  ],
})
