import { execFileSync } from 'node:child_process'
import { readdirSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'

const srcDir = new URL('../src/', import.meta.url)
const repoRoot = fileURLToPath(new URL('../../../', import.meta.url))
const header = '// Generated by scripts/generateIcons.mjs. Do not edit.\n'

const names = readdirSync(new URL('svg/', srcDir))
  .filter(file => file.endsWith('.svg'))
  .map(file => file.slice(0, -'.svg'.length))
  .sort((a, b) => a.localeCompare(b))

if (names.length === 0) {
  throw new Error('No SVG files found in src/svg')
}

const iconNamesSource = `${header}export type IconName =\n${names.map(name => `  | '${name}'`).join('\n')}\n`

const iconMapSource = `${header}import { defineAsyncComponent, type Component } from 'vue'

import type { IconName } from './iconNames'

export const iconMap: Record<IconName, Component> = {
${names.map(name => `  '${name}': defineAsyncComponent(() => import('./svg/${name}.svg')),`).join('\n')}
}
`

writeFileSync(new URL('iconNames.ts', srcDir), iconNamesSource)
writeFileSync(new URL('iconMap.ts', srcDir), iconMapSource)

// The generated layout does not match oxfmt; format here so format:check stays green.
// A failure must stop the script instead of leaving an unformatted file behind.
execFileSync('pnpm', ['exec', 'oxfmt', '--write', 'packages/icons/src/iconNames.ts', 'packages/icons/src/iconMap.ts'], {
  cwd: repoRoot,
  stdio: 'inherit',
})
