<template>
  <nav :aria-label="labels.nav">
    <slot name="text" :start="startIndex" :end="endIndex" :total="props.totalCount">
      <p :class="SUMMARY_CLASS">{{ `第 ${startIndex} - ${endIndex}，共 ${props.totalCount} 筆結果` }}</p>
    </slot>
    <ul :class="LIST_CLASS">
      <li>
        <button type="button" :class="ITEM_CLASS" :aria-label="labels.prev" :disabled="currentPage <= 1" @click="goTo(currentPage - 1)">
          <hk-icon name="arrow-left" size="16" />
        </button>
      </li>
      <li v-for="item in items" :key="item.type === 'page' ? item.page : item.key">
        <button
          v-if="item.type === 'page'"
          type="button"
          :class="ITEM_CLASS"
          :aria-current="item.page === currentPage ? 'page' : undefined"
          @click="goTo(item.page)"
        >
          {{ item.page }}
        </button>
        <span v-else :class="ELLIPSIS_CLASS" aria-hidden="true">…</span>
      </li>
      <li>
        <button type="button" :class="ITEM_CLASS" :aria-label="labels.next" :disabled="currentPage >= pageCount" @click="goTo(currentPage + 1)">
          <hk-icon name="arrow-right" size="16" />
        </button>
      </li>
    </ul>
  </nav>
</template>

<script setup lang="ts">
import { computed, useModel } from 'vue'

import { HkIcon } from '@myfunnow/hakka-icons'

import { getPageItems } from '@/utils/pagination'

import type { HkPaginationEmits, HkPaginationProps, HkPaginationSlots } from './types'

// Utility classes are generated by the app's UnoCSS, which finds them through the banner comment in dist.
// Colors come from the brand CSS variables; the focus ring falls back to currentColor when no brand CSS is loaded.
const SUMMARY_CLASS = 'm-0 text-center text-sm text-[color:var(--hk-color-text-helper)]'
const LIST_CLASS = 'flex justify-center gap-2 mt-5 mb-0 mx-0 p-0 list-none'
const ELLIPSIS_CLASS = 'flex items-center justify-center min-w-6 h-6 text-sm text-[color:var(--hk-color-text-default)]'
const ITEM_CLASS =
  'flex items-center justify-center min-w-6 h-6 px-1 py-0 border-0 rounded bg-[color:transparent] enabled:cursor-pointer text-sm text-[color:var(--hk-color-text-default)] transition-colors duration-200 hover:enabled:bg-[color:var(--hk-color-primary-hover)] hover:enabled:text-[color:var(--hk-color-on-color)] active:enabled:bg-[color:var(--hk-color-primary-pressed)] active:enabled:text-[color:var(--hk-color-on-color)] aria-[current=page]:bg-[color:var(--hk-color-primary)] aria-[current=page]:text-[color:var(--hk-color-on-color)] disabled:text-[color:var(--hk-color-text-disabled)] disabled:cursor-not-allowed focus-visible:outline-2 focus-visible:outline-solid focus-visible:outline-[color:var(--hk-color-primary,currentColor)] focus-visible:outline-offset-2'

const props = withDefaults(defineProps<HkPaginationProps>(), { page: 1, pageSize: 10, visible: 7, ariaLabels: () => ({}) })

defineEmits<HkPaginationEmits>()

defineSlots<HkPaginationSlots>()

const page = useModel(props, 'page')

const labels = computed(() => ({ nav: '分頁', prev: '上一頁', next: '下一頁', ...props.ariaLabels }))
const pageCount = computed(() => Math.max(Math.ceil(props.totalCount / props.pageSize), 1))
const currentPage = computed(() => Math.min(Math.max(page.value, 1), pageCount.value))
const items = computed(() => getPageItems({ page: currentPage.value, pageCount: pageCount.value, pageSlot: props.visible }))
const startIndex = computed(() => (props.totalCount === 0 ? 0 : (currentPage.value - 1) * props.pageSize + 1))
const endIndex = computed(() => Math.min(currentPage.value * props.pageSize, props.totalCount))

function goTo(target: number) {
  if (target < 1 || target > pageCount.value || target === currentPage.value) {
    return
  }

  page.value = target
}
</script>
