// Do not edit directly. Generated by token-transformer.
// Source: figma/document/tokens/tokens.json + figma/funnow/tokens/tokens.json

export const colors = {
  black: {
    20: "#6e7479",
    30: "#555a5f",
    40: "#3d4144",
    50: "#252729",
    60: "#0d0e0e",
    70: "#000000",
    80: "#000000"
  },
  blue: {
    10: "#e2edf1",
    20: "#c4dbe3",
    30: "#a1c6d3",
    40: "#7eb1c3",
    50: "#5b9cb3",
    60: "#468196",
    70: "#366474",
    80: "#254550"
  },
  brown: {
    20: "#f2ede8",
    30: "#dfd4c8",
    40: "#ccbaa8",
    50: "#b9a087",
    60: "#a78768",
    70: "#8b6e51",
    80: "#6a543e"
  },
  gray: {
    10: "#ffffff",
    20: "#f4f4f5",
    30: "#ededed",
    40: "#dbdbdb",
    50: "#c1c1c2",
    60: "#a7a7a9",
    70: "#8e8e8f",
    80: "#747476"
  },
  green: {
    20: "#ebf5f1",
    30: "#c9e3da",
    40: "#a7d1c3",
    50: "#86c0ad",
    60: "#65af96",
    70: "#4d947c",
    80: "#3b7260"
  },
  lavender: {
    10: "#f0f1ff",
    20: "#ded4f2",
    30: "#cfc0ec",
    40: "#b099e0",
    50: "#9272d4",
    60: "#744bc8",
    70: "#5b34ac",
    80: "#462885"
  },
  orange: {
    10: "#ffeeeb",
    20: "#ffd8d1",
    30: "#ffad9e",
    40: "#ff816b",
    50: "#ff5537",
    60: "#ff2a05",
    70: "#d21f00",
    80: "#9e1800"
  },
  pinkish: {
    10: "#f4f1f1",
    20: "#e8e3e3",
    30: "#d1c7c7",
    40: "#baabab",
    50: "#a38f8f",
    60: "#8c7373",
    70: "#705c5c",
    80: "#544545"
  },
  purple: {
    10: "#e4e6fc",
    20: "#cdd1f9",
    30: "#b6bcf6",
    40: "#8993f0",
    50: "#5a69eb",
    60: "#2f42e5",
    70: "#192bc7",
    80: "#13219b"
  },
  red: {
    10: "#f2d9da",
    20: "#e5b2b5",
    30: "#d98c90",
    40: "#cc666b",
    50: "#c03f45",
    60: "#993338",
    70: "#73262a",
    80: "#4d1a1c"
  },
  teal: {
    20: "#9ce2e2",
    30: "#75d7d7",
    40: "#4dcbcb",
    50: "#34b2b2",
    60: "#288a8a",
    70: "#1d6363",
    80: "#113b3b"
  },
  yellow: {
    10: "#fff1d1",
    20: "#ffe19e",
    30: "#ffd06b",
    40: "#ffc038",
    50: "#ffb107",
    60: "#d18f00",
    70: "#9e6c00",
    80: "#6b4900"
  }
} as const

export default { colors }
