<template>
  <div v-bind="splitAttrs.root" :class="rootClass" :style="rootStyle">
    <template v-if="src && !isFailed">
      <picture :class="pictureClass">
        <source v-if="webpSrc" :srcset="webpSrc" type="image/webp" />
        <img
          ref="img"
          :src="src"
          :alt="alt"
          :loading="eager ? 'eager' : 'lazy'"
          v-bind="{ ...splitAttrs.img, ...imgAttrs }"
          @load="handleLoad"
          @error="handleError"
        />
      </picture>
      <div v-if="inheritColor" aria-hidden="true" :class="[LAYER_CLASS, 'bg-current', MASK_CLASS, fadeClass]" :style="maskStyle" />
    </template>
    <div v-if="gradient" :class="[LAYER_CLASS, 'hk-img__gradient', 'bg-no-repeat']" :style="{ backgroundImage: `linear-gradient(${gradient})` }" />
    <div v-if="$slots.placeholder && !isLoaded && !isFailed" :class="LAYER_CLASS">
      <slot name="placeholder" />
    </div>
    <div v-if="$slots.error && isFailed" :class="LAYER_CLASS">
      <slot name="error" />
    </div>
    <div class="hk-img__content relative flex-1 max-w-full">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMounted } from '@vueuse/core'
import { computed, normalizeClass, onMounted, ref, useAttrs, useTemplateRef, watch } from 'vue'

import { cn, toCssLength, toCssUrl } from '@/utils/css'
import { getWebpSrc, readWebpEnvironment } from '@/utils/image'

import type { HkImgEmits, HkImgProps, HkImgSlots } from './types'

// Utility classes are generated by the app's UnoCSS, which finds them through the banner comment in dist.
// Image, gradient, placeholder and error all stack on one spot; the root is sized by aspect-ratio.
const ROOT_CLASS = 'hk-img relative flex grow shrink-0 max-w-full max-h-full overflow-hidden'
const LAYER_CLASS = 'absolute inset-0 w-full h-full'
// The mask is one shorthand, with a -webkit- copy for Safari before 15.4. The address, position and size arrive as CSS
// variables (the size falls back to contain), so cover and contain share these classes and each one stays a literal
// string for the app's UnoCSS to find.
const MASK_CLASS =
  '[mask:var(--hk-img-mask)_var(--hk-img-mask-position,center)/var(--hk-img-mask-size,contain)_no-repeat] [-webkit-mask:var(--hk-img-mask)_var(--hk-img-mask-position,center)/var(--hk-img-mask-size,contain)_no-repeat]'

// Same duration and easing as the fade of Vuetify's v-img (0.3s, cubic-bezier(0.4, 0, 0.2, 1) is the default easing of transition-opacity)
const FADE_CLASS = 'transition-opacity duration-300'

// Attributes of the <img> element itself. Everything else, listeners included, belongs to the root like it does on v-img.
// Names are compared without dashes and in lower case, so `fetchpriority`, `fetchPriority` and `fetch-priority` all match.
const IMG_ATTRIBUTES = new Set(['crossorigin', 'decoding', 'draggable', 'fetchpriority', 'loading', 'referrerpolicy', 'sizes', 'srcset'])

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<HkImgProps>(), { fadeIn: true })
const emit = defineEmits<HkImgEmits>()

defineSlots<HkImgSlots>()

const attrs = useAttrs()
const imgRef = useTemplateRef<HTMLImageElement>('img')

const isMounted = useMounted()
const isLoaded = ref(false)
const isFailed = ref(false)
const naturalAspectRatio = ref<number>()

// twMerge lets a downstream class override a default one (`overflow-visible` replaces `overflow-hidden`)
const rootClass = computed(() => cn(ROOT_CLASS, attrs.class))

// Once mounted, the image starts transparent and loses `opacity-0` when loaded, so the transition runs from 0 to 1.
// The server and the first client render have no `opacity-0`, so an image in server HTML is never hidden. An image that
// is already loaded on mount never gets it, and a new src fades in again.
const fadeClass = computed(() => (props.fadeIn ? [FADE_CLASS, { 'opacity-0': isMounted.value && !isLoaded.value }] : undefined))

const splitAttrs = computed(() => {
  const root: Record<string, unknown> = {}
  const img: Record<string, unknown> = {}

  for (const [name, value] of Object.entries(attrs)) {
    if (name === 'class') {
      continue
    }

    if (IMG_ATTRIBUTES.has(name.replace(/-/g, '').toLowerCase())) {
      img[name] = value
    } else {
      root[name] = value
    }
  }

  return { root, img }
})

// `aspect-square`, `md:aspect-video`, `sm:(aspect-unset h-300px)`: a call site that sets the ratio with a class keeps it.
// An inline ratio would beat the class, and a CSS variable fallback would tie with custom values such as `aspect-1.8`.
const hasAspectClass = computed(() => /(^|[\s:(])aspect-/.test(normalizeClass(attrs.class)))

// <picture> only negotiates browser support, it doesn't check that the webp file exists, and a
// 404 on the selected <source> does not fall back to the <img>. The app's build guarantees the
// file, so there is deliberately no runtime fallback here.
// With a srcset the browser would pick the webp source and ignore the img's own candidates, so there is no webp then.
const webpSrc = computed(() => (splitAttrs.value.img.srcset || props.inheritColor ? undefined : getWebpSrc(props.src, readWebpEnvironment())))

// With no ratio, no aspect class and no height there is nothing to size the box by, so the <img> stays in the normal flow
// and sizes it like a plain <img> does. That also works in server HTML before any script runs. Otherwise the <img> is a
// layer on top of a box that is sized by the other rules. In flow, `h-full` means auto while the box has no height, and
// fills it when a class or a max-height gives it one.
const isImgInFlow = computed(() => props.aspectRatio === undefined && !hasAspectClass.value && props.height === undefined)

const pictureClass = computed(() => (isImgInFlow.value ? 'contents' : LAYER_CLASS))

const imgLayerClass = computed(() => (isImgInFlow.value ? 'block w-full h-full' : LAYER_CLASS))

// With inherit-color the real <img> stays for the alt text, the load and error events and the natural ratio, but is not
// painted: the mask layer is. The mask needs CORS, so the crossorigin attribute is fixed there.
const imgAttrs = computed(() => {
  if (props.inheritColor) {
    return { class: [imgLayerClass.value, 'opacity-0'], crossorigin: 'anonymous' as const }
  }

  return {
    class: [imgLayerClass.value, props.cover ? 'object-cover' : 'object-contain', fadeClass.value],
    // In flow the box has no height of its own, so a max-height on the box would not shrink the img. The img takes the
    // same limit and object-fit keeps its shape.
    style: { objectPosition: props.position, maxHeight: isImgInFlow.value ? toCssLength(props.maxHeight) : undefined },
  }
})

const maskStyle = computed(() => ({
  '--hk-img-mask': toCssUrl(props.src),
  '--hk-img-mask-position': props.position,
  '--hk-img-mask-size': props.cover ? 'cover' : undefined,
}))

// The prop wins, then an `aspect-*` class (left to the stylesheet), then the natural ratio, and the fallback only while
// there is nothing to show
const aspectRatio = computed(() => {
  if (props.aspectRatio !== undefined) {
    return props.aspectRatio
  }

  if (hasAspectClass.value) {
    return undefined
  }

  // In flow the <img> sizes the box itself
  if (naturalAspectRatio.value !== undefined && !isImgInFlow.value) {
    return naturalAspectRatio.value
  }

  const isEmpty = !props.src || isFailed.value

  return isEmpty ? props.fallbackAspectRatio : undefined
})

const rootStyle = computed(() => {
  return {
    width: toCssLength(props.width),
    height: toCssLength(props.height),
    maxWidth: toCssLength(props.maxWidth),
    maxHeight: toCssLength(props.maxHeight),
    minWidth: toCssLength(props.minWidth),
    minHeight: toCssLength(props.minHeight),
    aspectRatio: aspectRatio.value === undefined ? undefined : `${aspectRatio.value}`,
  }
})

watch(
  () => props.src,
  () => {
    isLoaded.value = false
    isFailed.value = false
    naturalAspectRatio.value = undefined
  }
)

// An SSR image has already loaded or failed before hydration, so its load and error events are
// gone. Read the result from the element once mounted.
onMounted(() => {
  const img = imgRef.value

  if (!img?.complete) {
    return
  }

  if (img.naturalWidth > 0) {
    handleLoad()
  } else {
    handleError()
  }
})

function handleLoad() {
  const { naturalWidth = 0, naturalHeight = 0 } = imgRef.value ?? {}

  if (naturalWidth && naturalHeight) {
    naturalAspectRatio.value = naturalWidth / naturalHeight
  }

  isLoaded.value = true
  emit('load', props.src)
}

function handleError() {
  isFailed.value = true
  emit('error', props.src)
}
</script>
