<template>
  <div v-bind="splitAttrs.root" :class="rootClass" :style="rootStyle">
    <picture v-if="src && !isFailed && !inheritColor" :class="LAYER_CLASS">
      <source v-if="webpSrc" :srcset="webpSrc" type="image/webp" />
      <img
        ref="img"
        :class="[LAYER_CLASS, cover ? 'object-cover' : 'object-contain', fadeClass]"
        :src="src"
        :alt="alt"
        :loading="eager ? 'eager' : 'lazy'"
        :style="{ objectPosition: position }"
        v-bind="splitAttrs.img"
        @load="handleLoad"
        @error="handleError"
      />
    </picture>
    <template v-else-if="src && !isFailed">
      <!-- The real <img> stays for the alt text, the load and error events and the natural ratio, but is not painted -->
      <img
        ref="img"
        :class="[LAYER_CLASS, 'opacity-0']"
        :src="src"
        :alt="alt"
        :loading="eager ? 'eager' : 'lazy'"
        v-bind="splitAttrs.img"
        crossorigin="anonymous"
        @load="handleLoad"
        @error="handleError"
      />
      <div aria-hidden="true" :class="[LAYER_CLASS, 'bg-current', MASK_CLASS, fadeClass]" :style="maskStyle" />
    </template>
    <div v-if="gradient" :class="[LAYER_CLASS, 'hk-img__gradient', 'bg-no-repeat']" :style="{ backgroundImage: `linear-gradient(${gradient})` }" />
    <div v-if="$slots.placeholder && !isLoaded && !isFailed" :class="LAYER_CLASS">
      <slot name="placeholder" />
    </div>
    <div v-if="$slots.error && isFailed" :class="LAYER_CLASS">
      <slot name="error" />
    </div>
    <div class="hk-img__content relative flex-1 max-w-full">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { computed, normalizeClass, onMounted, ref, useAttrs, useTemplateRef, watch } from 'vue'

import type { CssSize } from '@/types/css'
import { cn, toCssSize, toCssUrl } from '@/utils/css'
import { getWebpSrc, readWebpEnvironment } from '@/utils/image'

// Props, slots and events follow Vuetify's v-img so a call site can swap one for the other.
// The comments on the props are shown in Storybook, so they are written for people who do not code.
interface Props {
  /** Address of the image. Leave it empty to show the placeholder instead. */
  src: string
  /** Short text that describes the image. Screen readers read it, and it shows when the image cannot load. */
  alt?: string
  /** Fill the whole box and cut off what does not fit. By default the whole image is shown. */
  cover?: boolean
  /** Load the image right away. By default it loads when it comes close to the screen. */
  eager?: boolean
  /** Shape of the box: width divided by height, for example 1 (square) or 1.8. Without it, the box takes the shape of the image after it has loaded. */
  aspectRatio?: CssSize
  /** Width of the box. A number means pixels (320). Text is used as it is ("50%", "20rem"). */
  width?: CssSize
  /** Height of the box. A number means pixels (320). Text is used as it is ("50%", "20rem"). */
  height?: CssSize
  /** The box never gets wider than this. A number means pixels, text is used as it is. */
  maxWidth?: CssSize
  /** The box never gets taller than this. A number means pixels, text is used as it is. */
  maxHeight?: CssSize
  /** The box never gets narrower than this. A number means pixels, text is used as it is. */
  minWidth?: CssSize
  /** The box never gets shorter than this. A number means pixels, text is used as it is. */
  minHeight?: CssSize
  /** Which part of the image stays in view when it is cut off, for example "top" or "left center". */
  position?: string
  /** A color layer on top of the image. Write what goes inside the CSS linear-gradient(), for example: to bottom, rgba(0,0,0,0), rgba(0,0,0,0.4) */
  gradient?: string
  /**
   * For an svg with one color: paint its shape with the text color, so a class such as "text-yellow-50" changes its color.
   * An svg inside an <img> cannot read the page's color, so the shape is used as a CSS mask instead.
   */
  inheritColor?: boolean
  /** Shape of the box while there is nothing to show (no src, or the image failed), so the page does not jump. Same values as aspectRatio. */
  fallbackAspectRatio?: CssSize
  /** Fade the image in after it has loaded. The parent decides when, for example not while the page is still starting up. */
  fadeIn?: boolean
}

interface Emits {
  (event: 'load', src: string): void
  (event: 'error', src: string): void
}

// Utility classes are generated by the app's UnoCSS, which finds them through the banner comment in dist.
// Image, gradient, placeholder and error all stack on one spot; the root is sized by aspect-ratio.
const ROOT_CLASS = 'hk-img relative flex grow shrink-0 max-w-full max-h-full overflow-hidden'
const LAYER_CLASS = 'absolute inset-0 w-full h-full'
// The mask is one shorthand, with a -webkit- copy for Safari before 15.4. The address, position and size arrive as CSS
// variables (the size falls back to contain), so cover and contain share these classes and each one stays a literal
// string for the app's UnoCSS to find.
const MASK_CLASS =
  '[mask:var(--hk-img-mask)_var(--hk-img-mask-position,center)/var(--hk-img-mask-size,contain)_no-repeat] [-webkit-mask:var(--hk-img-mask)_var(--hk-img-mask-position,center)/var(--hk-img-mask-size,contain)_no-repeat]'

// Same duration and easing as the fade of Vuetify's v-img (0.3s, cubic-bezier(0.4, 0, 0.2, 1) is the default easing of transition-opacity)
const FADE_CLASS = 'transition-opacity duration-300'

// Attributes of the <img> element itself. Everything else, listeners included, belongs to the root like it does on v-img.
// Names are compared without dashes and in lower case, so `fetchpriority`, `fetchPriority` and `fetch-priority` all match.
const IMG_ATTRIBUTES = new Set(['crossorigin', 'decoding', 'draggable', 'fetchpriority', 'loading', 'referrerpolicy', 'sizes', 'srcset'])

defineOptions({ inheritAttrs: false })

const props = defineProps<Props>()
const emit = defineEmits<Emits>()

const attrs = useAttrs()
const imgRef = useTemplateRef<HTMLImageElement>('img')

const isLoaded = ref(false)
const isFailed = ref(false)
const naturalAspectRatio = ref<number>()

// twMerge lets a downstream class override a default one (`overflow-visible` replaces `overflow-hidden`)
const rootClass = computed(() => cn(ROOT_CLASS, attrs.class))

// The image starts transparent and loses `opacity-0` once loaded, so the transition runs from 0 to 1.
// An image that is already loaded when the prop turns on has no `opacity-0` and does not animate.
const fadeClass = computed(() => (props.fadeIn ? [FADE_CLASS, { 'opacity-0': !isLoaded.value }] : undefined))

const splitAttrs = computed(() => {
  const root: Record<string, unknown> = {}
  const img: Record<string, unknown> = {}

  for (const [name, value] of Object.entries(attrs)) {
    if (name === 'class') {
      continue
    }

    if (IMG_ATTRIBUTES.has(name.replace(/-/g, '').toLowerCase())) {
      img[name] = value
    } else {
      root[name] = value
    }
  }

  return { root, img }
})

// `aspect-square`, `md:aspect-video`, `sm:(aspect-unset h-300px)`: a call site that sets the ratio with a class keeps it.
// An inline ratio would beat the class, and a CSS variable fallback would tie with custom values such as `aspect-1.8`.
const hasAspectClass = computed(() => /(^|[\s:(])aspect-/.test(normalizeClass(attrs.class)))

// <picture> only negotiates browser support, it doesn't check that the webp file exists, and a
// 404 on the selected <source> does not fall back to the <img>. The app's build guarantees the
// file, so there is deliberately no runtime fallback here.
// With a srcset the browser would pick the webp source and ignore the img's own candidates, so there is no webp then.
const webpSrc = computed(() => (splitAttrs.value.img.srcset ? undefined : getWebpSrc(props.src, readWebpEnvironment())))

const maskStyle = computed(() => ({
  '--hk-img-mask': toCssUrl(props.src),
  '--hk-img-mask-position': props.position,
  '--hk-img-mask-size': props.cover ? 'cover' : undefined,
}))

// The prop wins, then an `aspect-*` class (left to the stylesheet), then the natural ratio, and the fallback only while
// there is nothing to show
const aspectRatio = computed(() => {
  if (props.aspectRatio !== undefined) {
    return props.aspectRatio
  }

  if (hasAspectClass.value) {
    return undefined
  }

  if (naturalAspectRatio.value !== undefined) {
    return naturalAspectRatio.value
  }

  const isEmpty = !props.src || isFailed.value

  return isEmpty ? props.fallbackAspectRatio : undefined
})

const rootStyle = computed(() => {
  return {
    width: toCssSize(props.width),
    height: toCssSize(props.height),
    maxWidth: toCssSize(props.maxWidth),
    maxHeight: toCssSize(props.maxHeight),
    minWidth: toCssSize(props.minWidth),
    minHeight: toCssSize(props.minHeight),
    aspectRatio: aspectRatio.value === undefined ? undefined : `${aspectRatio.value}`,
  }
})

watch(
  () => props.src,
  () => {
    isLoaded.value = false
    isFailed.value = false
    naturalAspectRatio.value = undefined
  }
)

// An SSR image has already loaded or failed before hydration, so its load and error events are
// gone. Read the result from the element once mounted.
onMounted(() => {
  const img = imgRef.value

  if (!img?.complete) {
    return
  }

  if (img.naturalWidth > 0) {
    handleLoad()
  } else {
    handleError()
  }
})

function handleLoad() {
  const { naturalWidth = 0, naturalHeight = 0 } = imgRef.value ?? {}

  if (naturalWidth && naturalHeight) {
    naturalAspectRatio.value = naturalWidth / naturalHeight
  }

  isLoaded.value = true
  emit('load', props.src)
}

function handleError() {
  isFailed.value = true
  emit('error', props.src)
}
</script>
