<template>
  <div v-bind="splitAttrs.root" :class="rootClass" :style="rootStyle">
    <template v-if="hasImg">
      <picture class="contents">
        <source v-if="webpSrc" :srcset="webpSrc" type="image/webp" />
        <img
          ref="img"
          :src="src"
          :alt="alt"
          :loading="eager ? 'eager' : 'lazy'"
          v-bind="{ ...splitAttrs.img, ...imgAttrs }"
          @load="handleLoad"
          @error="handleError"
        />
      </picture>
      <div v-if="inheritColor" aria-hidden="true" :class="[LAYER_CLASS, 'bg-current', MASK_CLASS, fadeClass]" :style="maskStyle" />
    </template>
    <div v-if="gradient" :class="[LAYER_CLASS, 'hk-img__gradient', 'bg-no-repeat']" :style="{ backgroundImage: `linear-gradient(${gradient})` }" />
    <div v-if="$slots.placeholder && !isLoaded && !isFailed" :class="LAYER_CLASS">
      <slot name="placeholder" />
    </div>
    <div v-if="$slots.error && isFailed" :class="LAYER_CLASS">
      <slot name="error" />
    </div>
    <div :class="contentClass">
      <slot />
    </div>
  </div>
</template>

<script setup lang="ts">
import { useMounted } from '@vueuse/core'
import { computed, onMounted, ref, useAttrs, useTemplateRef, watch } from 'vue'

import { cn, toCssUrl } from '@/utils/css'
import { getWebpSrc, readWebpEnvironment } from '@/utils/image'

import type { HkImgEmits, HkImgProps, HkImgSlots } from './types'

// Utility classes are generated by the app's UnoCSS, which finds them through the banner comment in dist.
// The box wraps its content like an inline image: as wide as the picture, at most as wide as the parent. To fill the
// parent, the call site adds `w-full`.
// A flex column, so that a max-height from the call site (`max-h-*`) can shrink the <img> inside it
const ROOT_CLASS = 'hk-img relative inline-flex flex-col align-top max-w-full max-h-full overflow-hidden'
// Gradient, placeholder, error and the inherit-color mask stack over the image
const LAYER_CLASS = 'absolute inset-0 w-full h-full'
const EMPTY_CLASS = 'w-full aspect-[1.8]'
// The <img> fills the box. A box with no height of its own takes the height that follows from the picture.
const IMG_CLASS = 'block w-full h-full min-h-0'
// The mask is one shorthand, with a -webkit- copy for Safari before 15.4. The address, position and size arrive as CSS
// variables (the size falls back to contain), so cover and contain share these classes and each one stays a literal
// string for the app's UnoCSS to find.
const MASK_CLASS =
  '[mask:var(--hk-img-mask)_var(--hk-img-mask-position,center)/var(--hk-img-mask-size,contain)_no-repeat] [-webkit-mask:var(--hk-img-mask)_var(--hk-img-mask-position,center)/var(--hk-img-mask-size,contain)_no-repeat]'

// Same duration and easing as the fade of Vuetify's v-img (0.3s, cubic-bezier(0.4, 0, 0.2, 1) is the default easing of transition-opacity)
const FADE_CLASS = 'transition-opacity duration-300'

// Attributes of the <img> element itself. Everything else, listeners included, belongs to the root like it does on v-img.
// Names are compared without dashes and in lower case, so `fetchpriority`, `fetchPriority` and `fetch-priority` all match.
const IMG_ATTRIBUTES = new Set(['crossorigin', 'decoding', 'draggable', 'fetchpriority', 'loading', 'referrerpolicy', 'sizes', 'srcset'])

defineOptions({ inheritAttrs: false })

const props = withDefaults(defineProps<HkImgProps>(), { fadeIn: true })
const emit = defineEmits<HkImgEmits>()

defineSlots<HkImgSlots>()

const attrs = useAttrs()
const imgRef = useTemplateRef<HTMLImageElement>('img')

const isMounted = useMounted()
const isLoaded = ref(false)
const isFailed = ref(false)

// Once mounted, the image starts transparent and loses `opacity-0` when loaded, so the transition runs from 0 to 1.
// The server and the first client render have no `opacity-0`, so an image in server HTML is never hidden. An image that
// is already loaded on mount never gets it, and a new src fades in again.
const fadeClass = computed(() => (props.fadeIn ? [FADE_CLASS, { 'opacity-0': isMounted.value && !isLoaded.value }] : undefined))

const splitAttrs = computed(() => {
  const root: Record<string, unknown> = {}
  const img: Record<string, unknown> = {}

  for (const [name, value] of Object.entries(attrs)) {
    if (name === 'class') {
      continue
    }

    if (IMG_ATTRIBUTES.has(name.replace(/-/g, '').toLowerCase())) {
      img[name] = value
    } else {
      root[name] = value
    }
  }

  return { root, img }
})

// <picture> only negotiates browser support, it doesn't check that the webp file exists, and a
// 404 on the selected <source> does not fall back to the <img>. The app's build guarantees the
// file, so there is deliberately no runtime fallback here.
// With a srcset the browser would pick the webp source and ignore the img's own candidates, so there is no webp then.
const webpSrc = computed(() => (splitAttrs.value.img.srcset || props.inheritColor ? undefined : getWebpSrc(props.src, readWebpEnvironment())))

// The <img> always stays in the normal flow and fills the box, so it also shows in server HTML before any script runs.
// Nothing here sizes the box: the call site does, with classes (`w-*`, `h-*`, `max-h-*`, `aspect-*`) or the ratio props, and
// without any of them the box takes the size of the picture, at most the width of the parent. object-fit crops or fits
// the picture inside the box.
const hasImg = computed(() => Boolean(props.src) && !isFailed.value)

// Without an <img> (no src, or it failed) nothing gives the box a size, and a failed picture should not leave a hole of 0
// height. So the box fills the parent and keeps a 1.8 : 1 shape, like the default placeholder of eatigo's etg-img. Classes
// from the call site (`w-*`, `aspect-*`) replace these two, and the `aspectRatio` prop is inline, so it wins over both.
const rootClass = computed(() => cn(ROOT_CLASS, !hasImg.value && EMPTY_CLASS, attrs.class))

// Overlay content covers the <img>. With no <img> it is part of the flow and gives the box its size.
const contentClass = computed(() => (hasImg.value ? 'hk-img__content absolute inset-0 flex' : 'hk-img__content relative'))

// With inherit-color the real <img> stays for the alt text, the load and error events and the size of the box, but is not
// painted: the mask layer is. The mask needs CORS, so the crossorigin attribute is fixed there.
const imgAttrs = computed(() => {
  if (props.inheritColor) {
    return { class: [IMG_CLASS, 'opacity-0'], crossorigin: 'anonymous' as const }
  }

  return {
    class: [IMG_CLASS, props.cover ? 'object-cover' : 'object-contain', fadeClass.value],
    style: { objectPosition: props.position },
  }
})

const maskStyle = computed(() => ({
  '--hk-img-mask': toCssUrl(props.src),
  '--hk-img-mask-position': props.position,
  '--hk-img-mask-size': props.cover ? 'cover' : undefined,
}))

// Only the prop writes an inline ratio. An `aspect-*` class (`aspect-square`, `md:aspect-video`) is left to the stylesheet,
// so a responsive ratio works. With both, the inline prop wins.
const rootStyle = computed(() => {
  return {
    aspectRatio: props.aspectRatio === undefined ? undefined : `${props.aspectRatio}`,
  }
})

watch(
  () => props.src,
  () => {
    isLoaded.value = false
    isFailed.value = false
  }
)

// An SSR image has already loaded or failed before hydration, so its load and error events are
// gone. Read the result from the element once mounted.
onMounted(() => {
  const img = imgRef.value

  if (!img?.complete) {
    return
  }

  if (img.naturalWidth > 0) {
    handleLoad()
  } else {
    handleError()
  }
})

function handleLoad() {
  isLoaded.value = true
  emit('load', props.src)
}

function handleError() {
  isFailed.value = true
  emit('error', props.src)
}
</script>
