name: Storybook
on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      # - name: Get Package Version 🏷
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@main
      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10
      - name: Set up Node.js
        uses: actions/setup-node@v7
        with:
          node-version: '22'
          cache: 'pnpm'
      - name: Package Install 📦
        run: |
          pnpm install --frozen-lockfile
      - name: Run Tests 🧘
        run: |
          pnpm vitest run
      - name: Build 🔧
        run: |
          export BASE_PATH=/hakka-ui/
          pnpm build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          target-folder: .
          branch: gh-pages
          clean: true
          force: true
          # tag: ${{ steps.package-version.outputs.current-version}}
