name: Storybook
on:
  push:
    branches:
      - main
permissions:
  contents: write # push the built Storybook to the gh-pages branch
  packages: read # install @myfunnow/* from GitHub Packages
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
        with:
          persist-credentials: false
      # - name: Get Package Version 🏷
      #   id: package-version
      #   uses: martinbeentjes/npm-get-version-action@main
      - name: Install dependencies
        uses: ./.github/actions/install-dependencies
        with:
          node-auth-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Run Tests 🧘
        run: |
          pnpm test
      - name: Build 🔧
        run: |
          export BASE_PATH=/hakka-ui/
          pnpm build-storybook
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: storybook-static
          target-folder: .
          branch: gh-pages
          clean: true
          force: true
          # tag: ${{ steps.package-version.outputs.current-version}}
